/**
 * TODO: USE PUPPETEER TO CRAWL SO THAT WE CAN CLICK ON THE MORE BUTTON
 * TO GET MORE CONTENT TO CRAWL SINCE WE CANT DO THAT WITH CHEERIO
 * 
 * THIS FILE WILL CONTAIN THE CODE FOR THE INITIAL CRWAWLER
 */